name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install
      run: yarn

    - name: Build
      run: yarn build

    - name: Tests
      run: yarn test